<?php

namespace mrcnpdlk\Validator;

class TestCase extends \PHPUnit\Framework\TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
